# coding: utf-8

"""
    Zarban Wallet API

    API for Zarban wallet services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: info@zarban.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from zarban.wallet.openapi_client.configuration import Configuration


class AdminRedemptionUpdateRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'status': 'str',
        'paya_tracking_code': 'str'
    }

    attribute_map = {
        'status': 'status',
        'paya_tracking_code': 'payaTrackingCode'
    }

    def __init__(self, status=None, paya_tracking_code=None, local_vars_configuration=None):  # noqa: E501
        """AdminRedemptionUpdateRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._status = None
        self._paya_tracking_code = None
        self.discriminator = None

        self.status = status
        if paya_tracking_code is not None:
            self.paya_tracking_code = paya_tracking_code

    @property
    def status(self):
        """Gets the status of this AdminRedemptionUpdateRequest.  # noqa: E501

        The status of the redemption request  # noqa: E501

        :return: The status of this AdminRedemptionUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AdminRedemptionUpdateRequest.

        The status of the redemption request  # noqa: E501

        :param status: The status of this AdminRedemptionUpdateRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["Approved", "Rejected", "Completed"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def paya_tracking_code(self):
        """Gets the paya_tracking_code of this AdminRedemptionUpdateRequest.  # noqa: E501

        The Paya tracking code  # noqa: E501

        :return: The paya_tracking_code of this AdminRedemptionUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._paya_tracking_code

    @paya_tracking_code.setter
    def paya_tracking_code(self, paya_tracking_code):
        """Sets the paya_tracking_code of this AdminRedemptionUpdateRequest.

        The Paya tracking code  # noqa: E501

        :param paya_tracking_code: The paya_tracking_code of this AdminRedemptionUpdateRequest.  # noqa: E501
        :type: str
        """

        self._paya_tracking_code = paya_tracking_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminRedemptionUpdateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdminRedemptionUpdateRequest):
            return True

        return self.to_dict() != other.to_dict()
