# coding: utf-8

"""
    Zarban Wallet API

    API for Zarban wallet services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: info@zarban.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from zarban.wallet.openapi_client.configuration import Configuration


class Timestamp(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'jalaali': 'str',
        'gregorian': 'str'
    }

    attribute_map = {
        'jalaali': 'jalaali',
        'gregorian': 'gregorian'
    }

    def __init__(self, jalaali=None, gregorian=None, local_vars_configuration=None):  # noqa: E501
        """Timestamp - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._jalaali = None
        self._gregorian = None
        self.discriminator = None

        self.jalaali = jalaali
        self.gregorian = gregorian

    @property
    def jalaali(self):
        """Gets the jalaali of this Timestamp.  # noqa: E501

        Jalaali date  # noqa: E501

        :return: The jalaali of this Timestamp.  # noqa: E501
        :rtype: str
        """
        return self._jalaali

    @jalaali.setter
    def jalaali(self, jalaali):
        """Sets the jalaali of this Timestamp.

        Jalaali date  # noqa: E501

        :param jalaali: The jalaali of this Timestamp.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and jalaali is None:  # noqa: E501
            raise ValueError("Invalid value for `jalaali`, must not be `None`")  # noqa: E501

        self._jalaali = jalaali

    @property
    def gregorian(self):
        """Gets the gregorian of this Timestamp.  # noqa: E501

        Gregorian date  # noqa: E501

        :return: The gregorian of this Timestamp.  # noqa: E501
        :rtype: str
        """
        return self._gregorian

    @gregorian.setter
    def gregorian(self, gregorian):
        """Sets the gregorian of this Timestamp.

        Gregorian date  # noqa: E501

        :param gregorian: The gregorian of this Timestamp.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and gregorian is None:  # noqa: E501
            raise ValueError("Invalid value for `gregorian`, must not be `None`")  # noqa: E501

        self._gregorian = gregorian

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Timestamp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Timestamp):
            return True

        return self.to_dict() != other.to_dict()
