# coding: utf-8

"""
    Zarban API

    API for Zarban services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from zarban.service.openapi_client.configuration import Configuration


class Stats(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'stablecoin_system': 'StablecoinSystemStats',
        'lendingpool': 'LendingpoolStats'
    }

    attribute_map = {
        'stablecoin_system': 'stablecoinSystem',
        'lendingpool': 'lendingpool'
    }

    def __init__(self, stablecoin_system=None, lendingpool=None, local_vars_configuration=None):  # noqa: E501
        """Stats - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._stablecoin_system = None
        self._lendingpool = None
        self.discriminator = None

        self.stablecoin_system = stablecoin_system
        self.lendingpool = lendingpool

    @property
    def stablecoin_system(self):
        """Gets the stablecoin_system of this Stats.  # noqa: E501


        :return: The stablecoin_system of this Stats.  # noqa: E501
        :rtype: StablecoinSystemStats
        """
        return self._stablecoin_system

    @stablecoin_system.setter
    def stablecoin_system(self, stablecoin_system):
        """Sets the stablecoin_system of this Stats.


        :param stablecoin_system: The stablecoin_system of this Stats.  # noqa: E501
        :type: StablecoinSystemStats
        """
        if self.local_vars_configuration.client_side_validation and stablecoin_system is None:  # noqa: E501
            raise ValueError("Invalid value for `stablecoin_system`, must not be `None`")  # noqa: E501

        self._stablecoin_system = stablecoin_system

    @property
    def lendingpool(self):
        """Gets the lendingpool of this Stats.  # noqa: E501


        :return: The lendingpool of this Stats.  # noqa: E501
        :rtype: LendingpoolStats
        """
        return self._lendingpool

    @lendingpool.setter
    def lendingpool(self, lendingpool):
        """Sets the lendingpool of this Stats.


        :param lendingpool: The lendingpool of this Stats.  # noqa: E501
        :type: LendingpoolStats
        """
        if self.local_vars_configuration.client_side_validation and lendingpool is None:  # noqa: E501
            raise ValueError("Invalid value for `lendingpool`, must not be `None`")  # noqa: E501

        self._lendingpool = lendingpool

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Stats):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Stats):
            return True

        return self.to_dict() != other.to_dict()
