# coding: utf-8

"""
    Zarban Wallet API

    API for Zarban wallet services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: info@zarban.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import zarban.wallet.openapi_client
from zarban.wallet.openapi_client.api.withdraw_api import WithdrawApi  # noqa: E501
from zarban.wallet.openapi_client.rest import ApiException


class TestWithdrawApi(unittest.TestCase):
    """WithdrawApi unit test stubs"""

    def setUp(self):
        self.api = zarban.wallet.openapi_client.api.withdraw_api.WithdrawApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_withdraw_requests(self):
        """Test case for get_user_withdraw_requests

        Get user withdraw requests  # noqa: E501
        """
        pass

    def test_get_withdrawal_status(self):
        """Test case for get_withdrawal_status

        Get withdrawal status  # noqa: E501
        """
        pass

    def test_preview_withdrawal(self):
        """Test case for preview_withdrawal

        Withdraw request  # noqa: E501
        """
        pass

    def test_request_withdrawal(self):
        """Test case for request_withdrawal

        Withdraw request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
