# coding: utf-8

"""
    Zarban Wallet API

    API for Zarban wallet services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response200 import InlineResponse200  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse200(unittest.TestCase):
    """InlineResponse200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse200
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response200.InlineResponse200()  # noqa: E501
        if include_optional :
            return InlineResponse200(
                nickname = '0', 
                transactions = [
                    openapi_client.models.transaction.Transaction(
                        id = 56, 
                        time = openapi_client.models.timestamp.Timestamp(
                            jalaali = '1399-01-01T00:00:00Z', 
                            gregorian = '2020-01-01T00:00:00Z', ), 
                        type = 'Credit', 
                        from = '0', 
                        to = '0', 
                        symbol = 'USD', 
                        amount = {"USD":"1.23","TMN":"45.67","ZAR":"89.01","ETH":"0.02"}, 
                        external_transaction = openapi_client.models.external_transaction.ExternalTransaction(
                            id = 56, 
                            time = openapi_client.models.timestamp.Timestamp(
                                jalaali = '1399-01-01T00:00:00Z', 
                                gregorian = '2020-01-01T00:00:00Z', ), 
                            type = 'Credit', 
                            hash = '0', 
                            from = '0', 
                            to = '0', 
                            comment = '0', 
                            amount = {"USD":"1.23","TMN":"45.67","ZAR":"89.01","ETH":"0.02"}, 
                            symbol = 'USD', 
                            network = openapi_client.models.network.Network(
                                name = {"en_US":"Zar Stablecoin","fa_IR":"استیبل کوین زر"}, 
                                logo_uri = '0', ), 
                            status = 'Sent', ), )
                    ], 
                referral = openapi_client.models.referral.Referral(
                    id = 56, 
                    referrer_id = 56, 
                    name = '0', 
                    usage_limit = 56, 
                    usage_count = 56, 
                    created_at = openapi_client.models.timestamp.Timestamp(
                        jalaali = '1399-01-01T00:00:00Z', 
                        gregorian = '2020-01-01T00:00:00Z', ), 
                    link = 'https://t.me/zarbanwalletbot?start=referral-29', ), 
                points = 56, 
                avatar = 'https://example.com/avatar.json', 
                telegram = openapi_client.models.telegram_profile.TelegramProfile(
                    id = 56, 
                    username = '0', 
                    first_name = '0', 
                    last_name = '0', 
                    photo_url = '0', )
            )
        else :
            return InlineResponse200(
                nickname = '0',
                transactions = [
                    openapi_client.models.transaction.Transaction(
                        id = 56, 
                        time = openapi_client.models.timestamp.Timestamp(
                            jalaali = '1399-01-01T00:00:00Z', 
                            gregorian = '2020-01-01T00:00:00Z', ), 
                        type = 'Credit', 
                        from = '0', 
                        to = '0', 
                        symbol = 'USD', 
                        amount = {"USD":"1.23","TMN":"45.67","ZAR":"89.01","ETH":"0.02"}, 
                        external_transaction = openapi_client.models.external_transaction.ExternalTransaction(
                            id = 56, 
                            time = openapi_client.models.timestamp.Timestamp(
                                jalaali = '1399-01-01T00:00:00Z', 
                                gregorian = '2020-01-01T00:00:00Z', ), 
                            type = 'Credit', 
                            hash = '0', 
                            from = '0', 
                            to = '0', 
                            comment = '0', 
                            amount = {"USD":"1.23","TMN":"45.67","ZAR":"89.01","ETH":"0.02"}, 
                            symbol = 'USD', 
                            network = openapi_client.models.network.Network(
                                name = {"en_US":"Zar Stablecoin","fa_IR":"استیبل کوین زر"}, 
                                logo_uri = '0', ), 
                            status = 'Sent', ), )
                    ],
                referral = openapi_client.models.referral.Referral(
                    id = 56, 
                    referrer_id = 56, 
                    name = '0', 
                    usage_limit = 56, 
                    usage_count = 56, 
                    created_at = openapi_client.models.timestamp.Timestamp(
                        jalaali = '1399-01-01T00:00:00Z', 
                        gregorian = '2020-01-01T00:00:00Z', ), 
                    link = 'https://t.me/zarbanwalletbot?start=referral-29', ),
                points = 56,
        )

    def testInlineResponse200(self):
        """Test InlineResponse200"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
