# coding: utf-8

"""
    Zarban Wallet API

    API for Zarban wallet services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: info@zarban.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import zarban.wallet.openapi_client
from zarban.wallet.openapi_client.api.redemptions_api import RedemptionsApi  # noqa: E501
from zarban.wallet.openapi_client.rest import ApiException


class TestRedemptionsApi(unittest.TestCase):
    """RedemptionsApi unit test stubs"""

    def setUp(self):
        self.api = zarban.wallet.openapi_client.api.redemptions_api.RedemptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_redemptions(self):
        """Test case for get_all_redemptions

        Get all redemptions  # noqa: E501
        """
        pass

    def test_get_redemption_details(self):
        """Test case for get_redemption_details

        Get redemption  # noqa: E501
        """
        pass

    def test_redeem_zar(self):
        """Test case for redeem_zar

        Redeem zar  # noqa: E501
        """
        pass

    def test_update_redemption_status(self):
        """Test case for update_redemption_status

        Update redemption  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
