# coding: utf-8

"""
    Zarban API

    API for Zarban services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: info@zarban.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import zarban.service.openapi_client
from zarban.service.openapi_client.models.account_staking_summary import AccountStakingSummary  # noqa: E501
from zarban.service.openapi_client.rest import ApiException

class TestAccountStakingSummary(unittest.TestCase):
    """AccountStakingSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AccountStakingSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = zarban.service.openapi_client.models.account_staking_summary.AccountStakingSummary()  # noqa: E501
        if include_optional :
            return AccountStakingSummary(
                total_stake = {"USD":"1.23","TMN":"45.67","ZAR":"89.01","ETH":"0.02"}, 
                unclaimed_reward = {"USD":"1.23","TMN":"45.67","ZAR":"89.01","ETH":"0.02"}, 
                net_apy = '0.30'
            )
        else :
            return AccountStakingSummary(
                total_stake = {"USD":"1.23","TMN":"45.67","ZAR":"89.01","ETH":"0.02"},
                unclaimed_reward = {"USD":"1.23","TMN":"45.67","ZAR":"89.01","ETH":"0.02"},
                net_apy = '0.30',
        )

    def testAccountStakingSummary(self):
        """Test AccountStakingSummary"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
