# coding: utf-8

"""
    Zarban API

    API for Zarban services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.permission import Permission  # noqa: E501
from openapi_client.rest import ApiException

class TestPermission(unittest.TestCase):
    """Permission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Permission
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.permission.Permission()  # noqa: E501
        if include_optional :
            return Permission(
                id = 56, 
                timestamp = openapi_client.models.timestamp.Timestamp(
                    jalaali = '1399-01-01T00:00:00Z', 
                    gregorian = '2020-01-01T00:00:00Z', ), 
                where = openapi_client.models.address.Address(
                    label = 'vat', 
                    address = '0x1234567890123456789012345678901234567890', ), 
                who = openapi_client.models.address.Address(
                    label = 'vat', 
                    address = '0x1234567890123456789012345678901234567890', ), 
                action = 'rely'
            )
        else :
            return Permission(
                id = 56,
                timestamp = openapi_client.models.timestamp.Timestamp(
                    jalaali = '1399-01-01T00:00:00Z', 
                    gregorian = '2020-01-01T00:00:00Z', ),
                where = openapi_client.models.address.Address(
                    label = 'vat', 
                    address = '0x1234567890123456789012345678901234567890', ),
                who = openapi_client.models.address.Address(
                    label = 'vat', 
                    address = '0x1234567890123456789012345678901234567890', ),
                action = 'rely',
        )

    def testPermission(self):
        """Test Permission"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
