# coding: utf-8

"""
    Zarban API

    API for Zarban services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.update_order_request import UpdateOrderRequest  # noqa: E501
from openapi_client.rest import ApiException

class TestUpdateOrderRequest(unittest.TestCase):
    """UpdateOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateOrderRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.update_order_request.UpdateOrderRequest()  # noqa: E501
        if include_optional :
            return UpdateOrderRequest(
                order_hash = 'a'
            )
        else :
            return UpdateOrderRequest(
                order_hash = 'a',
        )

    def testUpdateOrderRequest(self):
        """Test UpdateOrderRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
