# coding: utf-8

"""
    Zarban API

    API for Zarban services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: info@zarban.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import zarban.service.openapi_client
from zarban.service.openapi_client.api.prices_api import PricesApi  # noqa: E501
from zarban.service.openapi_client.rest import ApiException


class TestPricesApi(unittest.TestCase):
    """PricesApi unit test stubs"""

    def setUp(self):
        self.api = zarban.service.openapi_client.api.prices_api.PricesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_prices(self):
        """Test case for list_prices

        List prices based on query parameters  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
