# coding: utf-8

"""
    Zarban API

    API for Zarban services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.lendingpool_deposit_tx_request import LendingpoolDepositTxRequest  # noqa: E501
from openapi_client.rest import ApiException

class TestLendingpoolDepositTxRequest(unittest.TestCase):
    """LendingpoolDepositTxRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LendingpoolDepositTxRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.lendingpool_deposit_tx_request.LendingpoolDepositTxRequest()  # noqa: E501
        if include_optional :
            return LendingpoolDepositTxRequest(
                user = '0x1234567890123456789012345678901234567890', 
                symbol = 'ETH', 
                amount = '10000000000000000000'
            )
        else :
            return LendingpoolDepositTxRequest(
                user = '0x1234567890123456789012345678901234567890',
                symbol = 'ETH',
        )

    def testLendingpoolDepositTxRequest(self):
        """Test LendingpoolDepositTxRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
