# coding: utf-8

"""
    Zarban API

    API for Zarban services.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: info@zarban.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import zarban.service.openapi_client
from zarban.service.openapi_client.api.deposits_api import DepositsApi  # noqa: E501
from zarban.service.openapi_client.rest import ApiException


class TestDepositsApi(unittest.TestCase):
    """DepositsApi unit test stubs"""

    def setUp(self):
        self.api = zarban.service.openapi_client.api.deposits_api.DepositsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_deposits(self):
        """Test case for get_user_deposits

        Get user deposits of Lendingpool  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
